### PR TITLE
Change class name

### PR DESCRIPTION
**Pull request by ghost**
### What's new?

Changed the name of the `.contacts_contact` class to `.contacts_wrapper`, because `.contacts_contact` is like a tautology

### CODE REVIEW

**Comment by ai** [comment]
Let’s replace to `.contant_item` instead

**Comment by ghost** [comment]
Do you mean `.contacts_item`? Just you wrote `.contant_item`

**Comment by ai** [comment]
Yes, autocorrection by phone :D

`.contacts_item`

**Comment by ghost** [comment]
I have done

**Pull request merged**
