### PR TITLE
 Unlock title selection

### PR DESCRIPTION
**Pull request by alkhasov**
Solution for the issue from https://twitter.com/st00nsa/status/1098279698176638976

### CODE REVIEW

**Comment by ai** [comment]
Thanks

**Comment by ai** [comment]
Can you also set `top: 0` inside `@media` in separated PR? I am in airplane, hard to fix it from the phone.

**Comment by alkhasov** [comment]
You mean in the next one, `@media (width <= 980px)`?

**Comment by ai** [comment]
Yeap.

**Comment by ai** [comment]
And you can remove `padding: 0` some it is default value

**Comment by ai** [comment]
Oh, no. You do not need to change `top`. My fail.

**Pull request merged**
